#include <rAgc>//Anti gun cheats -Rogue
#include <Opba>//Anti airbreak\teleport - Rogue
#include <rAct>//Anti car trolls - Rogue
#include <AntiJC>//Anti jetpack cheats- Rogue
#include <rEac>//Anti carswing\particlespam - Lorenc_
#include <rAmc>//Anti money cheats- Rogue
#include <rAntiBuggers>//Anti bug cheats.
#include <AFkill> //Anti fake kill -Rogue
#include <AntiFC>//Anti fake clients - Rogue
#include <rAsc>//Anti speed cheats- Rogue
#include <rVM>//Anti illegal car mods -Emmet_
#include <rAcs>//Anti car spam - Rogue
